//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProductDetAss
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERTAB1
    {
        public int Custid { get; set; }
        public string Custname { get; set; }
        public Nullable<int> produid { get; set; }
    
        public virtual PRODUCTSTAB1 PRODUCTSTAB1 { get; set; }
    }
}
