//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProductDetAss
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTSTAB1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTSTAB1()
        {
            this.CUSTOMERTAB1 = new HashSet<CUSTOMERTAB1>();
        }
    
        public int produid { get; set; }
        public string produname { get; set; }
        public Nullable<int> produrate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERTAB1> CUSTOMERTAB1 { get; set; }
    }
}
